
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-03
owner: ucsb-cs156-s26
repo_name: team01-s26-03
pull_requests: [{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01-30","number":58,"title":"Alexandrugherghescu01 30","url":"https://github.com/ucsb-cs156-s26/team01-s26-03/pull/58"},{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01-29","number":57,"title":"Alexandrugherghescu01 29","url":"https://github.com/ucsb-cs156-s26/team01-s26-03/pull/57"},{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01-28","number":56,"title":"Alexandrugherghescu01 28","url":"https://github.com/ucsb-cs156-s26/team01-s26-03/pull/56"},{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01-27","number":47,"title":"Alexandrugherghescu01 27","url":"https://github.com/ucsb-cs156-s26/team01-s26-03/pull/47"},{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01-26","number":44,"title":"Add MenuItemReview table","url":"https://github.com/ucsb-cs156-s26/team01-s26-03/pull/44"}]
